version: "2"

formatters:
  enable:
    - gofumpt

linters:
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

